### ISSUE TITLE
add option to scroll unselected panes

### ISSUE THREAD

**Issue by woutgg** [NHDaly/tmux-scroll-copy-mode#3]
Before the mouse overhaul, automatic enter/exit of copy mode also worked on other panes than the active one, i.e., the one over which the mouse cursor is located instead.
It would be nice to have this behaviour again since this allows for easier and quicker use of scrollback buffers.

**Comment by NHDaly** [comment]
Oooph, you're right. This is not great. Any ideas what the configuration change should be?

**Comment by NHDaly** [comment]
Looks like add `select-pane -t=;` before `copy-mode` will do the trick, credit @milosivanovic: https://github.com/tmux/tmux/issues/145#issuecomment-151123624.

I'm adding that now.

**Comment by woutgg** [comment]
Yes, that fix seems to work great, thanks!
However, the same change is required for the WheelDownPane event, so I think it looks like below.
(This also fixes the scroll-on-first-event issue mentioned in the other thread.)

``` shell
  tmux bind-key -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' \"select-pane -t= \; $enter_copy_mode_cmd \; send-keys -M\""
  tmux bind-key -n WheelDownPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' \"select-pane -t= \; send-keys -M\""
```

**Comment by NHDaly** [comment]
Thanks, good point; I realized that too after adding just the first line.

I was actually able to get this to work with the much simpler `tmux bind-key -n WheelDownPane send-keys -M -t =`.

I added these two lines in fd78e441c. This should now be fixed.

**Comment by NHDaly** [comment]
Ah, never mind. I was missing a detail: the way I had it, it didn't _select_ the pane, just scrolled in it. I've changed it now to your suggestion. Thanks @woutgg.

Fixed in 19e602f795f08.

**Comment by NHDaly** [comment]
Also, I've added c28119ac90045 which adds an option @scroll-without-changing-pane, off by default, to allow scrolling without selecting the pane.

This is not how `tmux 2.0` worked, but I prefer it working this way. :) Thanks again @woutgg.

**Comment by woutgg** [comment]
Great @NHDaly! Thanks so much for your effort! I had not even noticed the pane selection issue yet.

Two remarks:
- With `scroll-in-moused-over-pane` disabled, wheel-scrolling from a non-selected pane causes almost no actual scrolling in the active pane. It may be a glitch, it might be my setup...can you confirm/deny this?
- It looks like the `send_keys_to_tmux_cmd` variable is never used? Did you mean to use it in the wheeldown event command?

**Comment by NHDaly** [comment]
:) no problem. Thanks for the thorough followups!
- Yes, I have noticed this behavior as well. I'm not currently sure what to do about it. The problem is that `send-keys -M` does nothing if it's not over the current window, but `copy-mode` doesn't care where your mouse is. :/ It might be that I just shouldn't expose this option at all, because turning it off sucks.
  Maybe there is some clever way to say "if the mouse isn't over the current shell, do nothing"? Or, what I think would be ideal, is with this option disabled just send all the scroll events to the _selected_ window, no matter where the mouse is. But I'm not sure how to do that either.
- Good catch. You're right, I used it at first, but later realized it's not needed because the `-t=` in the `if-shell`s is sufficient. I have deleted `send_keys_to_tmux_cmd` in b4eff146a2a.

**Comment by woutgg** [comment]
Could this a bug in `send-keys` then?

I've noticed a second, similar effect. To reproduce:
- have `scroll-in-moused-over-pane` enabled
- create a window with two panes
- wheel-scroll up in one of them (call it _a_)
- do the same in the other (call it _b_)
- scroll for a bit again in _a_ and notice how _b_ also scrolls 1-3 lines every now and then as well (both directions); but scrolling in _b_ does not influence _a_ in this way

It does not seem to matter which one is the selected pane, and adding `-t=` to `send-keys` does not change anything as you already mentioned. I'm at a loss here.

**Comment by NHDaly** [comment]
Hmm, I do not notice that effect at all. :(

BUT, that said, you did cause me to find another bug, which is that as I had it, selecting the moused-over pane only happened when _entering copy-mode_ but not when scrolling once you were already _in_ copy-mode.

To fix that i've added a `select-pane -t=` to before the `send-keys -M` for the `#{pane_in_mode}` case: Fixed in 893e1b1ddde5d34280d3a30be7438b07d3da4d5b.

**Comment by woutgg** [comment]
Maybe it was due to your last fix, the glitch I described seems to be gone. I'm happily scrolling away now. :)
Thanks again for your work!

**Comment by NHDaly** [comment]
:D Glad to hear it! Thank _you_ for being so persistent and going through
this with me!

Me too!!! <_scroll scroll scroll_>

**Comment by woutgg** [comment]
:D
